---
- name: Loadbalancer Setup
  hosts: local
  become: yes

  tasks:
    - name: Enabled modules
      command: >
             a2enmod proxy
                     proxy_http
                     proxy_balancer
                     lbmethod_byrequests

    - name: Copying loadbalancer configuration file
      copy:
          src: /home/vagrant/loadbalancer/000-default.conf
          dest: /etc/apache2/sites-available/000-default.conf

    - name: Restart Apache Server
      service:
          name: apache2
          state: restarted     
